### PR TITLE
Added new fields to document edit page and deleted irrelevant fields from the edit page

### LINKED ISSUE #9: Create new input fields based on relevant info
Based on the prototype built from #4, we need to create the same fields and field names in the frontend. This includes getting rid of the old metadata fields and syncing up variable names with the other stacks for consistency. Creating the new fields should mean that the document page has the correct number of fields and the correct labels.

**Estimated time:** 1 hour
_Justification: Ran was in charge of frontend in the previous assignment, so she knows where the files are allocated and which elements to update. Workload will be based on how much metadata to delete/add._

**Frontend Acceptance Criteria:** 
The website page contains all the fields specified in the prototype. All the interactive fields respond correctly with user input.

### PR DESCRIPTION
**Pull request by LunaFang1016**
[Notes: we acknowledge the code changed in this PR is over 250 lines but we decided to keep this in one PR because we added 4 dictionaries in app.js to store options needed for drop-down menus, among which "acceptedCountries" (249 lines with country letter code as keys and country names as labels) and "acceptedDesiredPrograms" (58 lines, with all master's programs in CMU's school of computer science, carnegie institute of technology, and dietrich college) are big in code length. Considering they are in repetitive structure and contain similar information, we decided to keep them in one PR.]
1) Added new required fields in "Student Data", (originally "Primary Metadata"), including "Name", "Application Date", "Resume", and other optional input fields.
Screenshot 2022-10-04 223100

2) Added new required fields in "Academic History", (originally "Additional Metadata"), including "Desired Program", "Undergraduate University", "Major", "GPA", and other optional input fields.
Screenshot 2022-10-04 223148

3) Changed input box titles and placeholder text accordingly.

### CODE REVIEW

**Comment by cmkolb8** [comment]
LGTM!

**Comment by LunaFang1016** [comment]
1) Added desired programs in CMU SCS, CIT and DC colleges to "Desired Program" drop-down menu.
Screenshot 2022-10-05 170542

2) Converted undergrad university, major and minor input fields to text type and added placeholder text.
Screenshot 2022-10-05 161016

3) Fixed display problem in race drop-down menu.
Screenshot 2022-10-05 170828

**Comment by cmkolb8** [comment]
This looks good to me!

**Review by alice-nie — APPROVED** [review]
lgtm!

**Pull request merged**
