### PR TITLE
reformatted the backend of the form

### LINKED ISSUE #6: Add new metadata fields to the document entity with the set and get functionality
- [x] Remove all old fields

We need the backend to be able to store all the new fields we're planning for the form. We'll also delete old fields so that there's no clutter and so that we're keeping the code running efficiently. We do this by adding the relevant variable names and parameters to multiple files and connecting them to their respective names used in the database. The new fields added to the document entity will be used throughout the codebase.

**Estimated time:** 2 hours
_Justification: Replacing these fields shouldn’t take too long itself, but it is important to have the model correct with relevant names to ensure success throughout the rest of the project. Added a bit of time to come up with quality variable names and make sure they are relevant to their values._

**Backend Acceptance Criteria:** runs, complies, passes backend tests, saves, and gives the correct values for each field

### LINKED ISSUE #7: Get and set the value of each new field when a document is created, updated, or turned into a pdf.
We need to add a get and set function for each new field that we are adding to the document entity. These functions will get the value from the input and set the value into the database for each field. This allows users to easily use the interface, which abstracts from where we store the data, while the backend serving as the tool between the two.

**Estimated time:** 2 hours
_Justification: There are a few files and multiple places in each file I will have to edit in order to add these new statistics, which will probably take a few hours._

**Backend Acceptance Criteria:** runs, complies, passes backend tests, saves, and gives the correct values for each field

### LINKED ISSUE #8: Add the new metadata fields to the SQL to retrieve the saved values from the database.
We need to actually add the new fields which are being created to the SQL string so that they are actually gotten from the database. This string will get the requested fields from the database. We then need to call all of the get and set function to store the values we have received from the database.

**Estimated time:** 4 hours
_Justification: In the previous homework we ran into a problem with this step; added buffer time to help with debugging._

**Backend Acceptance Criteria:** runs, complies, passes backend tests, saves, and gives the correct values for each field

### PR DESCRIPTION
**Pull request by cmkolb8**
I added all the new fields to the document entity as well as deleted all of the old ones. I then added both the get and set functions for every new field so each field could be gotten from the inputted value. I then deleted all old get and set fields. I then edited the SQL string to get these new fields, and used the get and set methods to actually get the response from the database and save each respective value. 

[Notes: we acknowledge the code changed in this PR is over 250 lines but we decided to keep this in one PR because  the logic throughout is the exact same, we are just doing it for every single variable. Thus, although there are a lot of lines of code, there are only like three logic steps throughout.]

Altered six files to update the metadata form fields to those described in #3.

### CODE REVIEW

**Review by alice-nie — CHANGES_REQUESTED** [review]
I think some of the code might still be from the old prototype.

We can probably get rid of birthdate (71-73) and state (83-85), while we need to add email, minor, program application, MCAT, LSAT, GRE, GMAT, and resume (which might be what additional files is right now)

**Review by LunaFang1016 — COMMENTED** [review]
LGTM!

**Comment by cmkolb8** [comment]
> I think some of the code might still be from the old prototype.
> 
> We can probably get rid of birthdate (71-73) and state (83-85), while we need to add email, minor, program application, MCAT, LSAT, GRE, GMAT, and resume (which might be what additional files is right now)

Oh your'e right! I fixed this as well as added the rest of the functionality if someone can take a look!

**Review by alice-nie — CHANGES_REQUESTED** [review]
Fix naming inconsistency with additional notes! 
- line 53 Document.java: DOC_ADDITIONALNOTES_C
- line 90 in DocumentDao and line 243 in LuceneIndexingHandler: DOC_ADDITIONAL_NOTES_C

also, I think you kept DOC_GRADMAJOR_C in DocumentDao (line 90) but deleted it in Document.java (old line 107). I think we want to get rid of GRADMAJOR in DocumentDao since we already have a DOC_MAJOR_C.

minor/stylistic things:
- Line 99 in Document.java, comment says application date but I think it should say resume
- Line 166 in Document.java, comment says Major, but it's for DOC_SHARED_C
- lines 150-169 in DocumentDto.java, is there a reason GPA and GMAT are capitalized but mcat, lsat, and gre are lowercase?

**Comment by cmkolb8** [comment]
> Fix naming inconsistency with additional notes!
> 
> * line 53 Document.java: DOC_ADDITIONALNOTES_C
> * line 90 in DocumentDao and line 243 in LuceneIndexingHandler: DOC_ADDITIONAL_NOTES_C
> 
> also, I think you kept DOC_GRADMAJOR_C in DocumentDao (line 90) but deleted it in Document.java (old line 107). I think we want to get rid of GRADMAJOR in DocumentDao since we already have a DOC_MAJOR_C.
> 
> minor/stylistic things:
> 
> * Line 99 in Document.java, comment says application date but I think it should say resume
> * Line 166 in Document.java, comment says Major, but it's for DOC_SHARED_C
> * lines 150-169 in DocumentDto.java, is there a reason GPA and GMAT are capitalized but mcat, lsat, and gre are lowercase?

Oh true I fixed the inconsistency. For gradmajor that is what I just called desired program so I knew what that was

**Review by alice-nie — APPROVED** [review]
lgtm!

**Comment by cmkolb8** [comment]
Decided to leave all in one pull request because the logic throughout is the exact same, we are just doing it for every single variable. Thus, although there are a lot of lines of code, there are only like three logic steps throughout.

**Pull request merged**
